# Project information
site_name: Vu Tran
site_description: Personal Website
site_author: Tran Le Vu
site_url: https://squidfunk.github.io/mkdocs-material/

# Repository
repo_name: stevietran/Blog
repo_url: https://github.com/stevietran/Blog.git

# Copyright
copyright: Copyright &copy; 2020 - 2020 Vu Tran

# Configuration
theme:
  name: material
  nav_style: dark
  features:
    - instant
    - tabs
  language: en
  palette:
    primary: deep orange
    accent: deep orange
  font:
    text: Roboto
    code: Roboto Mono

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/stevietran
    - icon: fontawesome/brands/twitter
    - icon: fontawesome/brands/linkedin

  # web app manifest
  manifest: manifest.webmanifest

# Google Analytics
google_analytics:
  - UA-XXXXXXXX-X
  - auto

# Extensions
markdown_extensions:
  # extension for block-style side contents such as summaries, notes, hints or warnings
  # https://github.com/squidfunk/mkdocs-material/blob/master/docs/extensions/admonition.md
  - admonition

  # adds syntax highlighting to code blocks
  # https://github.com/squidfunk/mkdocs-material/blob/master/docs/extensions/codehilite.md
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

#nav:
#    - Home: 'index.md'
#    - About: 'about.md'
#    - Guide: 'README.md'

    # Blog session
    # - Blogs:
        # Page: Confluence
        # - Confluence: 'Blogs/misc/confluence.md'

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      type: date